<template>
  <div class="page page-icon">
    <van-tabs
      v-model="tab"
      sticky
    >
      <van-tab title="用法示例">
        <van-cell-group title="基础用法">
          <van-cell>
            <van-col :span="6">
              <van-icon
                name="chat-o"
                :size="32"
              />
            </van-col>
            <van-col :span="6">
              <van-icon
                name="user-circle-o"
                :size="32"
              />
            </van-col>
          </van-cell>
        </van-cell-group>

        <van-cell-group title="徽标提示">
          <van-cell>
            <van-col :span="6">
              <van-icon
                name="chat-o"
                :size="32"
                dot
              />
            </van-col>
            <van-col :span="6">
              <van-icon
                name="chat-o"
                :size="32"
                :badge="9"
              />
            </van-col>
            <van-col :span="6">
              <van-icon
                name="chat-o"
                :size="32"
                badge="99+"
              />
            </van-col>
          </van-cell>
        </van-cell-group>

        <van-cell-group title="图标颜色">
          <van-cell>
            <van-col :span="6">
              <van-icon
                name="chat-o"
                :size="32"
                color="#1989fa"
              />
            </van-col>
            <van-col :span="6">
              <van-icon
                name="chat-o"
                :size="32"
                color="#07c160"
              />
            </van-col>
          </van-cell>
        </van-cell-group>

        <van-cell-group title="图标大小">
          <van-cell center>
            <van-col :span="6">
              <van-icon
                name="chat-o"
                :size="40"
              />
            </van-col>
            <van-col :span="6">
              <van-icon
                name="chat-o"
                size="3rem"
              />
            </van-col>
          </van-cell>
        </van-cell-group>
      </van-tab>

      <van-tab title="基础图标">
        <van-grid
          :column-num="4"
          :border="false"
        >
          <van-grid-item
            icon="success"
            text="success"
          />
          <van-grid-item
            icon="plus"
            text="plus"
          />
          <van-grid-item
            icon="cross"
            text="cross"
          />
          <van-grid-item
            icon="fail"
            text="fail"
          />
          <van-grid-item
            icon="arrow"
            text="arrow"
          />
          <van-grid-item
            icon="arrow-left"
            text="arrow-left"
          />
          <van-grid-item
            icon="arrow-up"
            text="arrow-up"
          />
          <van-grid-item
            icon="arrow-down"
            text="arrow-down"
          />
        </van-grid>
      </van-tab>

      <van-tab title="线框风格">
        <van-grid
          :column-num="4"
          :border="false"
        >
          <van-grid-item
            icon="location-o"
            text="location-o"
          />
          <van-grid-item
            icon="like-o"
            text="like-o"
          />
          <van-grid-item
            icon="star-o"
            text="star-o"
          />
          <van-grid-item
            icon="phone-o"
            text="phone-o"
          />
          <van-grid-item
            icon="setting-o"
            text="setting-o"
          />
          <van-grid-item
            icon="fire-o"
            text="fire-o"
          />
          <van-grid-item
            icon="coupon-o"
            text="coupon-o"
          />
          <van-grid-item
            icon="cart-o"
            text="cart-o"
          />
          <van-grid-item
            icon="shopping-cart-o"
            text="shopping-cart-o"
          />
          <van-grid-item
            icon="cart-circle-o"
            text="cart-circle-o"
          />
          <van-grid-item
            icon="friends-o"
            text="friends-o"
          />
          <van-grid-item
            icon="comment-o"
            text="comment-o"
          />
          <van-grid-item
            icon="gem-o"
            text="gem-o"
          />
          <van-grid-item
            icon="gift-o"
            text="gift-o"
          />
          <van-grid-item
            icon="point-gift-o"
            text="point-gift-o"
          />
          <van-grid-item
            icon="send-gift-o"
            text="send-gift-o"
          />
          <van-grid-item
            icon="service-o"
            text="service-o"
          />
          <van-grid-item
            icon="bag-o"
            text="bag-o"
          />
          <van-grid-item
            icon="todo-list-o"
            text="todo-list-o"
          />
          <van-grid-item
            icon="balance-list-o"
            text="balance-list-o"
          />
          <van-grid-item
            icon="close"
            text="close"
          />
          <van-grid-item
            icon="clock-o"
            text="clock-o"
          />
          <van-grid-item
            icon="question-o"
            text="question-o"
          />
          <van-grid-item
            icon="passed"
            text="passed"
          />
          <van-grid-item
            icon="add-o"
            text="add-o"
          />
          <van-grid-item
            icon="gold-coin-o"
            text="gold-coin-o"
          />
          <van-grid-item
            icon="info-o"
            text="info-o"
          />
          <van-grid-item
            icon="play-circle-o"
            text="play-circle-o"
          />
          <van-grid-item
            icon="pause-circle-o"
            text="pause-circle-o"
          />
          <van-grid-item
            icon="stop-circle-o"
            text="stop-circle-o"
          />
          <van-grid-item
            icon="warning-o"
            text="warning-o"
          />
          <van-grid-item
            icon="phone-circle-o"
            text="phone-circle-o"
          />
          <van-grid-item
            icon="music-o"
            text="music-o"
          />
          <van-grid-item
            icon="smile-o"
            text="smile-o"
          />
          <van-grid-item
            icon="thumb-circle-o"
            text="thumb-circle-o"
          />
          <van-grid-item
            icon="comment-circle-o"
            text="comment-circle-o"
          />
          <van-grid-item
            icon="browsing-history-o"
            text="browsing-history-o"
          />
          <van-grid-item
            icon="underway-o"
            text="underway-o"
          />
          <van-grid-item
            icon="more-o"
            text="more-o"
          />
          <van-grid-item
            icon="video-o"
            text="video-o"
          />
          <van-grid-item
            icon="shop-o"
            text="shop-o"
          />
          <van-grid-item
            icon="shop-collect-o"
            text="shop-collect-o"
          />
          <van-grid-item
            icon="share-o"
            text="share-o"
          />
          <van-grid-item
            icon="chat-o"
            text="chat-o"
          />
          <van-grid-item
            icon="smile-comment-o"
            text="smile-comment-o"
          />
          <van-grid-item
            icon="vip-card-o"
            text="vip-card-o"
          />
          <van-grid-item
            icon="award-o"
            text="award-o"
          />
          <van-grid-item
            icon="diamond-o"
            text="diamond-o"
          />
          <van-grid-item
            icon="volume-o"
            text="volume-o"
          />
          <van-grid-item
            icon="cluster-o"
            text="cluster-o"
          />
          <van-grid-item
            icon="wap-home-o"
            text="wap-home-o"
          />
          <van-grid-item
            icon="photo-o"
            text="photo-o"
          />
          <van-grid-item
            icon="gift-card-o"
            text="gift-card-o"
          />
          <van-grid-item
            icon="expand-o"
            text="expand-o"
          />
          <van-grid-item
            icon="medal-o"
            text="medal-o"
          />
          <van-grid-item
            icon="good-job-o"
            text="good-job-o"
          />
          <van-grid-item
            icon="manager-o"
            text="manager-o"
          />
          <van-grid-item
            icon="label-o"
            text="label-o"
          />
          <van-grid-item
            icon="bookmark-o"
            text="bookmark-o"
          />
          <van-grid-item
            icon="bill-o"
            text="bill-o"
          />
          <van-grid-item
            icon="hot-o"
            text="hot-o"
          />
          <van-grid-item
            icon="hot-sale-o"
            text="hot-sale-o"
          />
          <van-grid-item
            icon="new-o"
            text="new-o"
          />
          <van-grid-item
            icon="new-arrival-o"
            text="new-arrival-o"
          />
          <van-grid-item
            icon="goods-collect-o"
            text="goods-collect-o"
          />
          <van-grid-item
            icon="eye-o"
            text="eye-o"
          />
          <van-grid-item
            icon="balance-o"
            text="balance-o"
          />
          <van-grid-item
            icon="refund-o"
            text="refund-o"
          />
          <van-grid-item
            icon="birthday-cake-o"
            text="birthday-cake-o"
          />
          <van-grid-item
            icon="user-o"
            text="user-o"
          />
          <van-grid-item
            icon="orders-o"
            text="orders-o"
          />
          <van-grid-item
            icon="tv-o"
            text="tv-o"
          />
          <van-grid-item
            icon="envelop-o"
            text="envelop-o"
          />
          <van-grid-item
            icon="flag-o"
            text="flag-o"
          />
          <van-grid-item
            icon="flower-o"
            text="flower-o"
          />
          <van-grid-item
            icon="filter-o"
            text="filter-o"
          />
          <van-grid-item
            icon="bar-chart-o"
            text="bar-chart-o"
          />
          <van-grid-item
            icon="chart-trending-o"
            text="chart-trending-o"
          />
          <van-grid-item
            icon="brush-o"
            text="brush-o"
          />
          <van-grid-item
            icon="bullhorn-o"
            text="bullhorn-o"
          />
          <van-grid-item
            icon="hotel-o"
            text="hotel-o"
          />
          <van-grid-item
            icon="cashier-o"
            text="cashier-o"
          />
          <van-grid-item
            icon="newspaper-o"
            text="newspaper-o"
          />
          <van-grid-item
            icon="warn-o"
            text="warn-o"
          />
          <van-grid-item
            icon="notes-o"
            text="notes-o"
          />
          <van-grid-item
            icon="calendar-o"
            text="calendar-o"
          />
          <van-grid-item
            icon="bulb-o"
            text="bulb-o"
          />
          <van-grid-item
            icon="user-circle-o"
            text="user-circle-o"
          />
          <van-grid-item
            icon="desktop-o"
            text="desktop-o"
          />
          <van-grid-item
            icon="apps-o"
            text="apps-o"
          />
          <van-grid-item
            icon="home-o"
            text="home-o"
          />
          <van-grid-item
            icon="back-top"
            text="back-top"
          />
          <van-grid-item
            icon="search"
            text="search"
          />
          <van-grid-item
            icon="points"
            text="points"
          />
          <van-grid-item
            icon="edit"
            text="edit"
          />
          <van-grid-item
            icon="delete"
            text="delete"
          />
          <van-grid-item
            icon="qr"
            text="qr"
          />
          <van-grid-item
            icon="qr-invalid"
            text="qr-invalid"
          />
          <van-grid-item
            icon="closed-eye"
            text="closed-eye"
          />
          <van-grid-item
            icon="down"
            text="down"
          />
          <van-grid-item
            icon="scan"
            text="scan"
          />
          <van-grid-item
            icon="free-postage"
            text="free-postage"
          />
          <van-grid-item
            icon="certificate"
            text="certificate"
          />
          <van-grid-item
            icon="logistics"
            text="logistics"
          />
          <van-grid-item
            icon="contact"
            text="contact"
          />
          <van-grid-item
            icon="cash-back-record"
            text="cash-back-record"
          />
          <van-grid-item
            icon="after-sale"
            text="after-sale"
          />
          <van-grid-item
            icon="exchange"
            text="exchange"
          />
          <van-grid-item
            icon="upgrade"
            text="upgrade"
          />
          <van-grid-item
            icon="ellipsis"
            text="ellipsis"
          />
          <van-grid-item
            icon="circle"
            text="circle"
          />
          <van-grid-item
            icon="description"
            text="description"
          />
          <van-grid-item
            icon="records"
            text="records"
          />
          <van-grid-item
            icon="sign"
            text="sign"
          />
          <van-grid-item
            icon="completed"
            text="completed"
          />
          <van-grid-item
            icon="failure"
            text="failure"
          />
          <van-grid-item
            icon="ecard-pay"
            text="ecard-pay"
          />
          <van-grid-item
            icon="peer-pay"
            text="peer-pay"
          />
          <van-grid-item
            icon="balance-pay"
            text="balance-pay"
          />
          <van-grid-item
            icon="credit-pay"
            text="credit-pay"
          />
          <van-grid-item
            icon="debit-pay"
            text="debit-pay"
          />
          <van-grid-item
            icon="cash-on-deliver"
            text="cash-on-deliver"
          />
          <van-grid-item
            icon="other-pay"
            text="other-pay"
          />
          <van-grid-item
            icon="tosend"
            text="tosend"
          />
          <van-grid-item
            icon="pending-payment"
            text="pending-payment"
          />
          <van-grid-item
            icon="paid"
            text="paid"
          />
          <van-grid-item
            icon="aim"
            text="aim"
          />
          <van-grid-item
            icon="discount"
            text="discount"
          />
          <van-grid-item
            icon="idcard"
            text="idcard"
          />
          <van-grid-item
            icon="replay"
            text="replay"
          />
          <van-grid-item
            icon="shrink"
            text="shrink"
          />
        </van-grid>
      </van-tab>

      <van-tab title="实底风格">
        <van-grid
          :column-num="4"
          :border="false"
        >
          <van-grid-item
            icon="location"
            text="location"
          />
          <van-grid-item
            icon="like"
            text="like"
          />
          <van-grid-item
            icon="star"
            text="star"
          />
          <van-grid-item
            icon="phone"
            text="phone"
          />
          <van-grid-item
            icon="setting"
            text="setting"
          />
          <van-grid-item
            icon="fire"
            text="fire"
          />
          <van-grid-item
            icon="coupon"
            text="coupon"
          />
          <van-grid-item
            icon="cart"
            text="cart"
          />
          <van-grid-item
            icon="shopping-cart"
            text="shopping-cart"
          />
          <van-grid-item
            icon="cart-circle"
            text="cart-circle"
          />
          <van-grid-item
            icon="friends"
            text="friends"
          />
          <van-grid-item
            icon="comment"
            text="comment"
          />
          <van-grid-item
            icon="gem"
            text="gem"
          />
          <van-grid-item
            icon="gift"
            text="gift"
          />
          <van-grid-item
            icon="point-gift"
            text="point-gift"
          />
          <van-grid-item
            icon="send-gift"
            text="send-gift"
          />
          <van-grid-item
            icon="service"
            text="service"
          />
          <van-grid-item
            icon="bag"
            text="bag"
          />
          <van-grid-item
            icon="todo-list"
            text="todo-list"
          />
          <van-grid-item
            icon="balance-list"
            text="balance-list"
          />
          <van-grid-item
            icon="clear"
            text="clear"
          />
          <van-grid-item
            icon="clock"
            text="clock"
          />
          <van-grid-item
            icon="question"
            text="question"
          />
          <van-grid-item
            icon="checked"
            text="checked"
          />
          <van-grid-item
            icon="add"
            text="add"
          />
          <van-grid-item
            icon="gold-coin"
            text="gold-coin"
          />
          <van-grid-item
            icon="info"
            text="info"
          />
          <van-grid-item
            icon="play-circle"
            text="play-circle"
          />
          <van-grid-item
            icon="pause-circle"
            text="pause-circle"
          />
          <van-grid-item
            icon="stop-circle"
            text="stop-circle"
          />
          <van-grid-item
            icon="warning"
            text="warning"
          />
          <van-grid-item
            icon="phone-circle"
            text="phone-circle"
          />
          <van-grid-item
            icon="music"
            text="music"
          />
          <van-grid-item
            icon="smile"
            text="smile"
          />
          <van-grid-item
            icon="thumb-circle"
            text="thumb-circle"
          />
          <van-grid-item
            icon="comment-circle"
            text="comment-circle"
          />
          <van-grid-item
            icon="browsing-history"
            text="browsing-history"
          />
          <van-grid-item
            icon="underway"
            text="underway"
          />
          <van-grid-item
            icon="more"
            text="more"
          />
          <van-grid-item
            icon="video"
            text="video"
          />
          <van-grid-item
            icon="shop"
            text="shop"
          />
          <van-grid-item
            icon="shop-collect"
            text="shop-collect"
          />
          <van-grid-item
            icon="share"
            text="share"
          />
          <van-grid-item
            icon="chat"
            text="chat"
          />
          <van-grid-item
            icon="smile-comment"
            text="smile-comment"
          />
          <van-grid-item
            icon="vip-card"
            text="vip-card"
          />
          <van-grid-item
            icon="award"
            text="award"
          />
          <van-grid-item
            icon="diamond"
            text="diamond"
          />
          <van-grid-item
            icon="volume"
            text="volume"
          />
          <van-grid-item
            icon="cluster"
            text="cluster"
          />
          <van-grid-item
            icon="wap-home"
            text="wap-home"
          />
          <van-grid-item
            icon="photo"
            text="photo"
          />
          <van-grid-item
            icon="gift-card"
            text="gift-card"
          />
          <van-grid-item
            icon="expand"
            text="expand"
          />
          <van-grid-item
            icon="medal"
            text="medal"
          />
          <van-grid-item
            icon="good-job"
            text="good-job"
          />
          <van-grid-item
            icon="manager"
            text="manager"
          />
          <van-grid-item
            icon="label"
            text="label"
          />
          <van-grid-item
            icon="bookmark"
            text="bookmark"
          />
          <van-grid-item
            icon="bill"
            text="bill"
          />
          <van-grid-item
            icon="hot"
            text="hot"
          />
          <van-grid-item
            icon="hot-sale"
            text="hot-sale"
          />
          <van-grid-item
            icon="new"
            text="new"
          />
          <van-grid-item
            icon="new-arrival"
            text="new-arrival"
          />
          <van-grid-item
            icon="goods-collect"
            text="goods-collect"
          />
          <van-grid-item
            icon="eye"
            text="eye"
          />
          <van-grid-item
            icon="alipay"
            text="alipay"
          />
          <van-grid-item
            icon="wechat"
            text="wechat"
          />
          <van-grid-item
            icon="photograph"
            text="photograph"
          />
          <van-grid-item
            icon="youzan-shield"
            text="youzan-shield"
          />
          <van-grid-item
            icon="umbrella-circle"
            text="umbrella-circle"
          />
          <van-grid-item
            icon="bell"
            text="bell"
          />
          <van-grid-item
            icon="printer"
            text="printer"
          />
          <van-grid-item
            icon="map-marked"
            text="map-marked"
          />
          <van-grid-item
            icon="card"
            text="card"
          />
          <van-grid-item
            icon="add-square"
            text="add-square"
          />
          <van-grid-item
            icon="live"
            text="live"
          />
          <van-grid-item
            icon="lock"
            text="lock"
          />
          <van-grid-item
            icon="audio"
            text="audio"
          />
          <van-grid-item
            icon="graphic"
            text="graphic"
          />
          <van-grid-item
            icon="column"
            text="column"
          />
          <van-grid-item
            icon="invition"
            text="invition"
          />
          <van-grid-item
            icon="play"
            text="play"
          />
          <van-grid-item
            icon="pause"
            text="pause"
          />
          <van-grid-item
            icon="stop"
            text="stop"
          />
          <van-grid-item
            icon="weapp-nav"
            text="weapp-nav"
          />
          <van-grid-item
            icon="ascending"
            text="ascending"
          />
          <van-grid-item
            icon="descending"
            text="descending"
          />
          <van-grid-item
            icon="bars"
            text="bars"
          />
          <van-grid-item
            icon="wap-nav"
            text="wap-nav"
          />
          <van-grid-item
            icon="enlarge"
            text="enlarge"
          />
          <van-grid-item
            icon="photo-fail"
            text="photo-fail"
          />
        </van-grid>
      </van-tab>
    </van-tabs>
  </div>
</template>

<script>
export default {
  data() {
    return {
      tab: 0,
    };
  },
};
</script>

<style lang="less">
@import "../style/var";

.page-icon {
  .van-tab__pane {
    width: auto;
    margin: @padding-md;
    background-color: #fff;
    border-radius: 12px;
  }

  .van-col {
    display: inline-block;
    float: none;
    padding: @padding-md 0;
    vertical-align: middle;
    line-height: 1;
  }

  .van-grid-item__text {
    text-align: center;
  }
}
</style>
